<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>TS_Login</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>5b8621b1-f207-4887-be63-29353306152d</testSuiteGuid>
   <testCaseLink>
      <guid>ad90c100-9f7f-474b-87a8-61de4e916b73</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TC_LOGIN</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>2c78895d-1b90-4cb3-b076-1e5071a8bb37</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/DATA_LOGIN</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>2c78895d-1b90-4cb3-b076-1e5071a8bb37</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Username</value>
         <variableId>5bf36e0c-e5f9-4b6c-be10-33e807ec7be2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>2c78895d-1b90-4cb3-b076-1e5071a8bb37</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Password</value>
         <variableId>186a8819-3cba-4b7b-9891-af9c42282320</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
